config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
    @article = Article.new
  end
  def create
    # @article = article.new(params[:article])
    @article = Article.new(article_params)
    @article.save
    redirect_to root_path
  end
  def edit
    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to root_path
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end
  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>
<%= link_to 'Back', root_path %>

app/views/articles/index.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <h2>
      <%= link_to(article.title, article_path(article)) %>
    </h2>
    <p>
      <%= article.content %>
    </p>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/articles/show.html.erb
<div class="container">
  <h1>Article</h1>
    <p>
      <%= link_to 'Edit article', edit_article_path %>
      <%= link_to 'Delete', article_path, method: :delete, ata: { confirm: "Are you sure?" } %>
    </p>
    <p>
      <%= @article.content %>
    </p>
  <%= link_to 'Back', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <div class="navbar-wagon">
      <!-- Logo -->
      <a href="/" class="navbar-wagon-brand">Wikinimous</a>
    </div>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>